"""adjsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
import survay.views as mview
import adjauth.views as myauth
# from django.conf.urls import include, url
# from .settings import DEBUG
from django.urls import path, include

handler403 = mview.my_custom_permission_denied_view

urlpatterns = [
    path('', mview.index, name='index_page'),
    path('survay/nav/', mview.mainindex, name='main_page'),
    path('survay/projects/list/',
         mview.ProjectsList.as_view(),
         name='projects_list'),
    path('survay/projects/detail/<int:pk>/',
         mview.ProjectsDetail.as_view(),
         name='projects_detail'),
    path('survay/create',
         mview.ProjectsCreate.as_view(),
         name='projects_create'),
    path('survay/projects/list/<int:pk>/',
         mview.ProjectsUpdate.as_view(),
         name='projects_update'),
    path('handbookobjects/list/',
         mview.HandbookObjectsList.as_view(),
         name='handbookobjects_list'),
    path('handbookobjects/detail/<int:pk>/',
         mview.HandbookObjectsDetail.as_view(),
         name='handbookobjects_detail'),
    path('handbookobjects/create',
         mview.HandbookObjectsCreate.as_view(),
         name='handbookobjects_create'),
    path('handbookobjects/list/<int:pk>/',
         mview.HandbookObjectsUpdate.as_view(),
         name='handbookobjects_update'),
    path('survay/sprdolgn/list/',
         mview.FilteredSprDolgnList.as_view(),
         name='sprdolgn_list'),
    path('survay/sprdolgn/detail/<int:pk>/',
         mview.SprDolgnDetail.as_view(),
         name='sprdolgn_detail'),
    path('survay/sprdolgn/create',
         mview.SprDolgnCreate.as_view(),
         name='sprdolgn_create'),
    path('survay/sprdolgn/list/<int:pk>/',
         mview.SprDolgnUpdate.as_view(),
         name='sprdolgn_update'),
    path('survay/objects/list/',
         mview.FilteredObjectsList.as_view(),
         name='objects_list'),
    path('survay/objects/detail/<int:pk>/',
         mview.ObjectsDetail.as_view(),
         name='objects_detail'),
    path('survay/objects/create',
         mview.ObjectsCreate.as_view(),
         name='objects_create'),
    path('survay/objects/list/<int:pk>/',
         mview.ObjectsUpdate.as_view(),
         name='objects_update'),
    path('survay/objects/list/delete/<int:pk>/',
         mview.ObjectsDelete.as_view(),
         name='objects_delete'),
    path('survay/typestreet/list/',
         mview.TypeStreetList.as_view(),
         name='typestreet_list'),
    path('survay/typestreet/detail/<int:pk>/',
         mview.TypeStreetDetail.as_view(),
         name='typestreet_detail'),
    path('survay/typestreet/create',
         mview.TypeStreetCreate.as_view(),
         name='typestreet_create'),
    path('survay/typestreet/list/<int:pk>/',
         mview.TypeStreetUpdate.as_view(),
         name='typestreet_update'),
    path('survay/objectspersonals/list/',
         mview.FilteredObjectsPersonalsList.as_view(),
         name='objectspersonals_list'),
    path('survay/objects/list/search/<int:objid>',
         mview.FilteredOneObjectsPersonalsList.as_view(),
         name='search_personals'),
    path('survay/objects/list/search/<int:objid>/create',
         mview.OneObjectsPersonalsCreate.as_view(),
         name='search_personals_create'),
    path('survay/objects/list/search/<int:objid>/<int:pk>/',
         mview.OneObjectsPersonalsUpdate.as_view(),
         name='search_personals_update'),
    path('survay/objects/list/search/detail/<int:pk>/',
         mview.OneObjectsPersonalsDetail.as_view(),
         name='search_personals_detail'),
    path('survay/objectspersonals/create',
         mview.ObjectsPersonalsCreate.as_view(),
         name='objectspersonals_create'),
    path('survay/objectspersonals/list/<int:pk>/',
         mview.ObjectsPersonalsUpdate.as_view(),
         name='objectspersonals_update'),
    path('survay/objectspersonals/detail/<int:pk>/',
         mview.ObjectsPersonalsDetail.as_view(),
         name='personals_detail'),
    path('survay/objectspersonals/list/delete/<int:pk>/',
         mview.ObjectsPersonalsDelete.as_view(),
         name='objectspersonals_delete'),
    path('survay/addresses/list/',
         mview.FilteredAddressesList.as_view(),
         name='addresses_list'),
    path('survay/addresses/detail/<int:pk>/',
         mview.AddressesDetail.as_view(),
         name='addresses_detail'),
    path('survay/addresses/create',
         mview.AddressesCreate.as_view(),
         name='addresses_create'),
    path('survay/addresses/list/delete/<int:pk>/',
         mview.AddressesDelete.as_view(),
         name='addresses_delete'),
    path('survay/addresses/list/<int:pk>/',
         mview.AddressesUpdate.as_view(),
         name='addresses_update'),
    path('survay/addresses/list/search/<int:addrid>/<int:pk>/',
         mview.ObjectsAddressUpdate.as_view(),
         name='search_objects_update'),
    path('survay/addresses/list/search/<int:addrid>/',
         mview.FilteredObjectsAddressList.as_view(),
         name='search_objects'),
    path('survay/addresses/list/search/create/?<int:addrid>',
         mview.ObjectsAddressCreate.as_view(),
         name='search_objects_create'),
    path('survay/addresses/list/search/<int:addrid>/objsearch/<int:objid>',
         mview.FilteredOneObjectsPersonalsList.as_view(),
         name='search_personals_objects'),
    path('survay/addresses/list/search/<int:addrid>/objsearch/<int:objid>/<int:pk>/',
         mview.OneObjectsPersonalsUpdate.as_view(),
         name='search_personals_objects_update'),

    path('survay/addresses/external',
         mview.external_api_view,
         name="adr_find_page"),
    path('survay/addresses/external/view',
         mview.external_view,
         name="adr_page"),
    path('survay/addresses/external/addresses_create',
         mview.external_address_create,
         name="adr_create_page"),
    # admin
    path('admin/', admin.site.urls),
    # users
    path('survay/crmpersonals/list/<int:groupid>/',
         mview.CRMPersonalsList.as_view(),
         name='crmpersonals_list'),
    path('survay/crmpersonals/list/<int:groupid>/create',
         mview.CRMPersonalsCreate.as_view(),
         name='crmpersonals_create'),
    path('survay/crmpersonals/list/<int:groupid>/<int:pk>/',
         mview.CRMPersonalsUpdate.as_view(),
         name='crmpersonals_update'),
    path('survay/crmpersonals/detail/<int:groupid>/<int:pk>/',
         mview.AddressesDetail.as_view(),
         name='addresses_detail'),
    path('survey/crmpersonals/list/<int:groupid>/changepass/<int:pk>/',
         mview.CRMPersonalsPassChangeView.as_view(),
         name='crmpersonals_pass_change'),
    # login
    # url(r"^accounts/", include("django.contrib.auth.urls")),
    # path('register/', myauth.RegisterUser.as_view(), name='register'),
    path('auth/login/', myauth.MyLoginView.as_view(), name='login'),
    path('auth/logout/', myauth.MyLogoutView.as_view(), name='logout'),
    # path('auth/user/create/',
    #      myauth.UserCreateView.as_view(),
    #      name='user_create'),
]

# if DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns
