# Generated by Django 3.2 on 2021-10-16 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookObjects',
            fields=[
                ('HandbookObjectID', models.IntegerField(primary_key=True, serialize=False, verbose_name='HandbookObjectID')),
                ('ObjectName', models.CharField(blank=True, help_text='Наименование типов объектов: поликлиника, аптека и т.п.', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я-_ ]+$', 'Разрешено использовать только буквы, пробел и дефис.', code='invalid_objectname')], verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Типы объектов',
                'verbose_name_plural': 'Типы объектов',
                'db_table': 'HandbookObjects',
            },
        ),
    ]
