# Generated by Django 3.2 on 2021-10-17 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprDolgn',
            fields=[
                ('SprDolgnID', models.IntegerField(primary_key=True, serialize=False, verbose_name='SprDolgnID')),
                ('DolgnName', models.CharField(blank=True, help_text='Наименование должностей или специальностей: провизор, врач-ревматолог и т.п.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я-_ ]+$', 'Разрешено использовать только буквы, пробел и дефис.', code='invalid_doljname')], verbose_name='Наименование')),
                ('InsertDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('HandbookObjectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handbookobjects', to='survay.handbookobjects', verbose_name='Код типа объекта')),
            ],
            options={
                'verbose_name': 'Справочник-Должности',
                'verbose_name_plural': 'Должности',
                'db_table': 'SprDolgn',
            },
        ),
    ]
