# Generated by Django 3.2 on 2021-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0004_alter_handbookobjects_handbookobjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprdolgn',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
