# Generated by Django 3.2 on 2021-10-17 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0005_alter_sprdolgn_insertdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False, verbose_name='ProjectID')),
                ('ProjectName', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я-_ ]+$', 'Разрешено использовать только буквы, пробел и дефис.', code='invalid_doljname')], verbose_name='Название проекта')),
                ('ProjectDesc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('isActive', models.PositiveSmallIntegerField(default=0, verbose_name='Активный')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('RemoteVisit', models.PositiveSmallIntegerField(default=0, verbose_name='Удаленные визиты')),
                ('VizitTime', models.PositiveSmallIntegerField(null=True, verbose_name='Время визитов')),
                ('NoGeo', models.PositiveSmallIntegerField(verbose_name='Гео-локация')),
                ('isNewObj', models.PositiveSmallIntegerField(null=True, verbose_name='isNewObj')),
                ('ArhivDate', models.DateTimeField(null=True, verbose_name='Дата блокировки')),
                ('PocketName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя пакета')),
                ('VersionNumber', models.PositiveIntegerField(null=True, verbose_name='VersionNumber')),
                ('PocketSize', models.PositiveIntegerField(null=True, verbose_name='Размер пакета')),
                ('WEB', models.PositiveSmallIntegerField(null=True, verbose_name='WEB')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projects',
            },
        ),
    ]
