# Generated by Django 3.2 on 2021-10-19 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0007_auto_20211019_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprdolgn',
            name='HandbookObjectID',
            field=models.ForeignKey(db_column='HandbookObjectID', on_delete=django.db.models.deletion.PROTECT, related_name='handbookobjects', to='survay.handbookobjects', verbose_name='Код типа объекта'),
        ),
    ]
