# Generated by Django 3.2 on 2021-10-20 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0008_alter_sprdolgn_handbookobjectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('ObjectID', models.AutoField(primary_key=True, serialize=False, verbose_name='ObjectID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я0-9-_ ]+$', 'Разрешено использовать только буквы,цифры, пробел и дефис.', code='invalid_titleobj')], verbose_name='Название объекта')),
                ('full_title', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я0-9-_ ]+$', 'Разрешено использовать только буквы,цифры, пробел и дефис.', code='invalid_titleobj')], verbose_name='Полное наименовае объекта')),
                ('categories', models.CharField(max_length=50, verbose_name='Категория')),
                ('StatusID', models.PositiveSmallIntegerField(default=0, verbose_name='Статус')),
                ('AddressID', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Адрес')),
                ('InsertDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
