# Generated by Django 3.2 on 2021-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0010_auto_20211020_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='StatusID',
            field=models.SmallIntegerField(default=0, verbose_name='Статус'),
        ),
    ]
