# Generated by Django 3.2 on 2021-10-21 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0011_alter_objects_statusid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeStreet', models.CharField(blank=True, help_text='Наименование типов: улица, переулок и т.п.', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я-_ ]+$', 'Разрешено использовать только буквы, пробел и дефис.', code='invalid_typestreet')], verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Типы улиц',
                'verbose_name_plural': 'Типы улиц',
                'db_table': 'TypeStreet',
            },
        ),
        migrations.AlterField(
            model_name='objects',
            name='full_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименовае объекта'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объекта'),
        ),
    ]
