# Generated by Django 3.2 on 2021-10-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0014_alter_typestreet_typestreet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='VObjects',
        ),
        migrations.CreateModel(
            name='ObjectsPersonals',
            fields=[
                ('ObjectPersonalID', models.AutoField(primary_key=True, serialize=False, verbose_name='ObjectPersonalID')),
                ('PersFam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('PersName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('PersLName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('PersPhone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('PersEmail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Адрес Е-почты')),
                ('Comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('StatusID', models.SmallIntegerField(default=0, verbose_name='Статус')),
                ('InsertDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ObjectID', models.ForeignKey(db_column='ObjectID', on_delete=django.db.models.deletion.PROTECT, related_name='vobjects', to='survay.vobjects', verbose_name='Код типа объекта')),
                ('SprDolgnID', models.ForeignKey(db_column='SprDolgnID', on_delete=django.db.models.deletion.PROTECT, related_name='sprdolgn', to='survay.sprdolgn', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персонал объектов',
                'verbose_name_plural': 'Персонал',
                'db_table': 'ObjectsPersonals',
            },
        ),
    ]
