# Generated by Django 3.2 on 2021-10-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survay', '0015_auto_20211021_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('AddressID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='AddressID')),
                ('Region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('SubRegion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Под-Регион')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город (Населенный пункт)')),
                ('Raion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('typestreet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип улицы')),
                ('house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('Gis2Address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес - строка')),
                ('InsertDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Адреса объектов',
                'verbose_name_plural': 'Адреса',
                'db_table': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='objectspersonals',
            name='ObjectID',
            field=models.ForeignKey(db_column='ObjectID', on_delete=django.db.models.deletion.PROTECT, related_name='vobjects', to='survay.vobjects', verbose_name='Объект'),
        ),
    ]
